Feature/auth
KirillKolyshkin/PartyCheck pull request #2
Opened 2019-04-24 10:30 UTC by KirillKolyshkin

2019-04-30 23:07 UTC, NailShaykhrazievItis requested changes

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/data/party/Party.kt
> +}
Add empty line after class

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/data/user/User.kt
> +}
Add empty line after class

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/domain/bd/DBProvider.kt
> +
empty line

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/domain/bd/DBProvider.kt
> +        title: String,
Я не сторонник такого стиля, ну да ладно. Вкусовщина

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/domain/bd/DBProvider.kt
> +    fun getCurrentUser(): Maybe<User> {
мог через равно написать

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/domain/bd/DBProvider.kt
> +}
Add empty line after class

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/domain/party/PartyModel.kt
> +             "MyPartyTest", "SomeDescription", "Itis", Date(12272000), "a", User(),
Ты мог по умолчанию как вариант задать все это, тип дефолтная переменная

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/domain/user/UserInteractor.kt
> +class UserInteractor(private val auth: FirebaseAuth, private val sharedPreferences: SharedPreferences) {
почему здесь нет переноса переменных в конструкторе. Если выбрал один стиль, пиши в нем

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/domain/user/UserInteractor.kt
> +}
Add empty line after class

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/di/module/InteractorModule.kt
> +}
Add empty line after class

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/dialog/CodeDialog.kt
> +
extra line

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/dialog/CodeDialog.kt
> +    override fun onClick(v: View) {
ну пусть, но как-то странно все это

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/dialog/CodeDialog.kt
> +}
Add empty line after class

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/dialog/CodeDialog.kt
> +        val intent = Intent()
Диалог не должен уметь замускать экраны. Пеередай или лямбду, или коллбек интерфейс

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/presenter/SignInPresenter.kt
> +
экстра лайн

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/presenter/SignInPresenter.kt
> +}
Add empty line after class

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/view/SignInFragment.kt
> +}
Add empty line after class

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/view/SignInFragment.kt
> +        fun newInstance(): SignInFragment {
```
fun newInstance(): SignInFragment = SignInFragment().apply {
arguments = Bundle(){
}
}
```

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/view/SignInView.kt
> +
extra line

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/view/SignInView.kt
> +}
Add empty line after class

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyActivity.kt
> +
==____==

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyFragment.kt
> +        val TAKE_PICTURE = 100
а почему это локальная переменная, тебе потом же результат еще ловить. Перекинь в компаньон обжект и сделай константой

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyFragment.kt
> +        val REQUEST_GET_SINGLE_FILE = 200
тоже самое

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyFragment.kt
> +            override fun beforeTextChanged(s: CharSequence, start: Int, count: Int, after: Int) {}
это можно было в экстеншен для едиттекста вынести, но не до этого

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyFragment.kt
> +            return AddPartyFragment()
=

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyPresenter.kt
> +
экстра лайн

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyPresenter.kt
> +}
Add empty line after class

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyView.kt
> +}
Add empty line after class

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyView.kt
> +
экстра лайн

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/view/PartyListFragment.kt
> +        inflater.inflate(R.layout.my_party_list, container, false)
fragment_my_party_list

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/profile/presenter/ProfilePresenter.kt
> +}
=_+

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/profile/view/ProfileFragment.kt
> +
extra line

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/profile/view/ProfileFragment.kt
>          when (editFieldsMode) {
а тут точно конструкция when, я слышал про иф елзе

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/profile/view/ProfileFragment.kt
> +        val ad = context?.let { AlertDialog.Builder(it) }
context?.let { AlertDialog.Builder(it) }?.apply{
setTitle()
setPositive()
...
}

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/profile/view/ProfileFragment.kt
> +        val TAKE_PICTURE = 100
писал выше

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/profile/view/ProfileFragment.kt
>  }
+

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/profile/view/ProfileView.kt
> +}
+

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/partycheckapp/presentation/feature/profile/view/ProfileView.kt
> +
экстра лайн

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/dialog_ver_code.xml
> +        />
ctrl+alt+L

2019-04-30 23:07 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/fragment_add_party.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
какой релатив. Депрекейтет!!!! КонстреинтЛайоут

2019-05-01 05:43 UTC, KirillKolyshkin commented on app/src/main/java/com/example/partycheckapp/domain/party/PartyModel.kt
> +             "MyPartyTest", "SomeDescription", "Itis", Date(12272000), "a", User(),
это тестовая, потом вообще оно выпилится

2019-05-01 05:46 UTC, KirillKolyshkin commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/dialog/CodeDialog.kt
> +        val intent = Intent()
он и не запускает, он просто данные во фрагмент отправляет

2019-05-14 18:31 UTC, closed without merging