Current version
KirillKolyshkin/PartyCheck pull request #3
Opened 2019-05-09 13:01 UTC by KirillKolyshkin

2019-05-13 13:44 UTC, Senkoraa requested changes

2019-05-13 13:44 UTC, Senkoraa commented on .idea/codeStyles/codeStyleConfig.xml
> +<component name="ProjectCodeStyleConfiguration">
Первое с чего стоит начать, это навык использования gitignore, туда должна быть включена вся папка .idea

2019-05-13 13:44 UTC, Senkoraa commented on app/build.gradle
> +    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
Если используешь androidx тебе это не нужно

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/PartyApp.kt
> +                .builder()
Это можно поднять на строку выше

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/PartyApp.kt
> +
Пустая строка тут не нужна

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/PartyApp.kt
> +        @JvmStatic lateinit var instance: PartyApp
Прочитай что такое @JvmStatic а потом подумай точно ли оно тебе нужно?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/data/debtors/Debt.kt
> +    constructor() : this(
Убери пожалуйста... для таких случаев делают значения по умолчанию в котлине

data class Debt(
	    val ref: String = "",
	    val debtor: User = User(),
	    val creditor: User = User(),
	    val debtSize: Double = 0.0,
	    var debtorApproval: Boolean = false,
	    var creditorApproval: Boolean = false
	)

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/data/party/Party.kt
> +    constructor() : this(
Аналогично предыдущему коментарию.

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/data/party/Party.kt
> +import java.util.*
Плохая идея делать wild card импорты.

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/data/party/Party.kt
> +import android.os.Parcelable
Как мне кажется этот импорт тут лишний.

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/data/party/Purchase.kt
> +import android.os.Parcelable
Аналогично

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/data/party/Purchase.kt
> +    constructor() : this(
Аналогично

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/data/user/User.kt
> +    constructor() : this("",  "", null, null)
Аналогично

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/data/user/UserWithFlag.kt
> +    constructor() : this("", "", null, null, false)
Аналогично

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/domain/user/UserInteractor.kt
> +                        //signInPresenter.authPassed()
Закоментировано значит не нужно.

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/domain/user/UserInteractor.kt
> +                        Log.d(TAG, "onVerificationCompleted:$credential")
Во-первых это не нужно, во-вторых это утечка данных. У тебя в логи будут сыпаться креды аутентификации.

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/domain/user/UserInteractor.kt
> +                        Log.d(TAG, "onCodeSent:$verificationId")
Точно надо?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/domain/user/UserInteractor.kt
> +                        //resendToken = token
Убери всё что закоментировано

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/domain/user/UserInteractor.kt
> +                        //signInWithPhoneAuthCredential(PhoneAuthProvider.getCredential(verificationId, "433155"), context)
Убери всё что закоментировано

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/domain/user/UserInteractor.kt
> +    private fun signInWithPhoneAuthCredential(credential: PhoneAuthCredential): Boolean {
Убери все коменты, если они не нужны тут. И ссылки на Логи тоже

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/di/component/AppComponent.kt
> +
Пустая строка

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/di/module/AppModule.kt
> +        private const val PREFS_KEY = "com.user.prefs"
Хреновенький ключ. Никакой уникальности обычно именуют пакетами проекта типо com.example.partycheckapp

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/di/module/InteractorModule.kt
> +    fun provideUserModule(fb: FirebaseAuth, sp: SharedPreferences) = UserInteractor(fb, sp)
Нейминг так себе. fb, sp а дальше? yoprst?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/di/module/InteractorModule.kt
> +    fun provideUserProvider(df: FirebaseFirestore, sp: SharedPreferences, fs: FirebaseStorage) = DBProvider(df, sp, fs)
provideUserProvider?? Может DB Provider?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/di/module/MainActivityrModule.kt
> +class MainActivityrModule {
Опечатка в названии модуля...ActivityR

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/di/module/MainActivityrModule.kt
> +    fun provideDebtorsListPresenter(userProvider: DBProvider) =
Определись со стилем, где-то в одну строку, где-то в 2

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/CodeDialog.kt
> +    val LOG_TAG = "myLogs"
Оно тебе надо? ещё и публичное в итоговом приложении

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/CodeDialog.kt
> +        Log.d(LOG_TAG, "Dialog 1: onDismiss")
Кажись лишнее

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/CodeDialog.kt
> +        Log.d(LOG_TAG, "Dialog 1: onCancel")
И это тоже

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/SignInFragment.kt
> +        auth = FirebaseAuth.getInstance()
Это можно @Inject сделать, у тебя же дагер это провайдит. И вообще зачем это во вью?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/SignInFragment.kt
> +    fun enterTheApp(){
Это наверное должно быть приватным? А ну и ещё автоформативароени рулит, ты пробел потерял " () { "

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/SignInPresenter.kt
> +    protected val compositeDisposable = CompositeDisposable()
Почему protected?
Когда я показывал protected это был вариант, когда объявляешь в базовом классе для презентеров, а если дать в каждом то нужно private объявлять.

2019-05-13 13:44 UTC, Senkoraa commented on app/build.gradle
> +    implementation "ru.terrakok.cicerone:cicerone:5.0.0"
Зачем он тебе если в проекте ты им не пользуешься?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/SignInFragment.kt
> +
Пустые строки убери

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/SignInFragment.kt
> +
Аналогично

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/auth/SignInFragment.kt
> +        val dlg1 = CodeDialog()
Что за адский нейминг? Откуда ты на копипастил? dlg1 супер понятно о чем речь...

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtorDetails/DebtorDetailsActivity.kt
> +                .replace(R.id.container, DebtorDetailsFragment.newInstance(debtId))
А почему нельзя было сделать просто в Activity? Зачем делать прослойку из фрагмента?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtorDetails/DebtorDetailsActivity.kt
> +        if (savedInstanceState == null) {
А что будет если будет !=null? экран будет пустым?)

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtorDetails/DebtorDetailsFragment.kt
> +        toolbar.title = "Debt Details"
Что за хардкодинг? Ресурсы для кого?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtorDetails/DebtorDetailsFragment.kt
> +        var localUser = User()
Это что за жесть и почему она в компаньене? Они должны быть статикой?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListAdapter.kt
> +class DebtorsListAdapter(private var onItemClick: (UserDebtor) -> Unit) : RecyclerView.Adapter<ViewHolder>() {
Почему var? И почему нельзя положить это как переменную?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListAdapter.kt
> +    fun addAll(values: List<UserDebtor>) {
Что за ад?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListAdapter.kt
> +class DebtorsListAdapter(private var onItemClick: (UserDebtor) -> Unit) : RecyclerView.Adapter<ViewHolder>() {
Почему не ListAdapter, который работает через DiffUtils и работает лучше?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListFragment.kt
> +
Строка

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListFragment.kt
> +
И ещё

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListFragment.kt
> +        val manager = LinearLayoutManager(context)
Бесполезная переменная, можно сразу присваивать

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListFragment.kt
> +        for (debt in dataList) {
Вот такие вещи делаются в презентере, а ещё лучше в мапере, во вью преобразования данных не происходят

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListFragment.kt
> +    override fun getUser(user: User) {
Тебе не кажется что это какой-то очень странный метод? Называется getUser, не возвращает ничего, при этом получает на вход User...

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListFragment.kt
> +        toolbar.title = "Debtor List"
Строку в Ресурсы

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListFragment.kt
> +        for (debt in debtList){
Можно же потоками делать без явного использования циклов

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListFragment.kt
> +        intent.putExtra("debt_ref", currentDebt.ref)
Зачем открывать возможно не существующую задолженность?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListFragment.kt
> +        var localMenu: Menu? = null
Зачем всё это в статике?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListPresenter.kt
> +    protected val compositeDisposable = CompositeDisposable()
уже писал

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyFragment.kt
> +                //val bitmap = (iv_photo.drawable as BitmapDrawable).bitmap
Удалить

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyFragment.kt
> +        startActivityForResult(Intent.createChooser(intent, "Select Picture"), REQUEST_GET_SINGLE_FILE)
Хард код...

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyFragment.kt
> +        ad?.setTitle("Choose Type")  // заголовок
Хард код

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyFragment.kt
> +            val title = et_title.text.toString().trim { it <= ' ' }
Где ты увидел такой странный trim?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyFragment.kt
> +            if (TextUtils.isEmpty(title)) {
Убери TextUtils... isEmpty есть у котлин строки

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyFragment.kt
> +        toolbar.title = "Add Party"
хард код

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyPresenter.kt
> +    fun addParty(title: String,
напиши нормально этот метод

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/partylist/PartyListFragment.kt
> +        toolbar.title = "My Parties"
хард код

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/partylist/PartyListFragment.kt
> +        val manager = LinearLayoutManager(context)
уже писал

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/partylist/PartyListFragment.kt
> +        for (party in localParties){
localParties.filter{ it.title.contains(textQuery)}

и никаких циклов

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/partylist/PartyListPresenter.kt
> +    protected val compositeDisposable = CompositeDisposable()
писал

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/partylist/ViewHolder.kt
> +            val sdf = SimpleDateFormat("dd/M/yyyy")
locale

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/partydetails/addpurchase/AddPurchaseFragment.kt
> +        val manager = LinearLayoutManager(context)
ну ты  понял

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/partydetails/addpurchase/AddPurchaseFragment.kt
> +        toolbar.title = "Add Purchase"
Хард код

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/partydetails/addpurchase/AddPurchaseFragment.kt
> +            if (TextUtils.isEmpty(title)) {
Выше писал

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/partydetails/addpurchase/AddPurchaseFragment.kt
> +        ad?.setTitle("Choose Type")  // заголовок
Хардкод.. и дублирование такие вещи нужно выносить в общие утилитарные классы

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/partydetails/addpurchase/AddPurchaseFragment.kt
> +                //val bitmap = (iv_photo.drawable as BitmapDrawable).bitmap
Коменты нужно удалять

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/partydetails/addpurchase/AddPurchaseFragment.kt
> +                //val bitmap = (iv_photo.drawable as BitmapDrawable).bitmap
Удалить

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/partydetails/addpurchase/AddPurchaseFragment.kt
> +        const val TAKE_PICTURE = 100
Эти константы нужны где-то кроме этого класса?

2019-05-13 13:44 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/partydetails/addpurchase/AddPurchasePresenter.kt
> +    protected val compositeDisposable = CompositeDisposable()
Доступность

2019-05-13 18:59 UTC, KirillKolyshkin commented on app/src/main/java/com/example/partycheckapp/PartyApp.kt
> +        @JvmStatic lateinit var instance: PartyApp
это не я писал, вы залили это когда рефачили на клин архитектуру и с даггером помогали

2019-05-13 20:07 UTC, KirillKolyshkin commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListFragment.kt
> +        intent.putExtra("debt_ref", currentDebt.ref)
если она закрыта с обеих сторон, то ее и не будет в списке, а если она не закрыта другой, значит первая может отменить оплату, в виду ошибки

2019-05-14 19:18 UTC, Senkoraa requested changes

2019-05-14 19:18 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/debtors/DebtorsListPresenter.kt
> +    private fun parseDebtToUserDebtor(debts: ArrayList<Debt>): ArrayList<UserDebtor> {
в идеале вынести в маппер

2019-05-14 19:18 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/party/addparty/AddPartyFragment.kt
>          var ad = context?.let { AlertDialog.Builder(it) }
мы уже говорили о нейминге

2019-05-14 19:18 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/partydetails/addpurchase/AddPurchaseFragment.kt
> +            startActivityForResult(cameraIntent, 100)
а вот это зря.. лучше использовать константы

2019-05-14 19:18 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/partydetails/addpurchase/AddPurchaseFragment.kt
> -        const val TAKE_PICTURE = 100
их можно сделать просто приватными а не удалить

2019-05-14 19:18 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/profile/ProfileFragment.kt
> +    private fun hideKeyboardFrom(context: Context, view: View) {
такие вещи выносят в утилитарные статические методы или экстеншены

2019-05-14 19:18 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/profile/ProfileFragment.kt
>          profilePresenter.updateUSer(name, phone, card.toString(), bitmap)
USer??

2019-05-14 19:18 UTC, Senkoraa commented on app/src/main/java/com/example/partycheckapp/presentation/feature/profile/ProfileFragment.kt
> -        val TAKE_PICTURE = 100
аналогично

2019-05-14 19:18 UTC, Senkoraa commented on app/src/main/res/layout/fragment_add_party.xml
> +                        android:maxLength="15"
плохая идея, в таких случаях делаю singleLine + elipsize = "end" он просто сделает троеточие н всё, что не влезет

2019-05-14 20:50 UTC, KirillKolyshkin commented on app/src/main/res/layout/fragment_add_party.xml
> +                        android:maxLength="15"
спасибо, вот это сейчас полезно очень было

2019-06-13 09:44 UTC, merged